### ISSUE TITLE
Install hangs

### ISSUE THREAD

**Issue by jackfirth** [cfinegan/atom-ide-racket#1]
When attempting to install via `apm` or the Atom GUI, installation hangs and never completes. Force quitting Atom, reopening, and attempting to install again then fails with an error complaining that the package lock could not be acquired.

I suspect it's because the `raco pkg install --skip-installed racket-langserver` command needs to install dependency packages (the `chk` one, probably) so it waits for input asking if it's okay to install the dependencies. Installing `racket-langserver` with the `--auto` flag might possibly fix this.

**Comment by cfinegan** [comment]
Thanks for reporting this. I verified the issue on my machine and added the `--auto` flag, which fixed the issue, so this should be resolved now.
